<?php

/**
 * @file
 * stanford_media.module
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\stanford_media\Form\MediaLibraryFileUploadForm;
use Drupal\stanford_media\Plugin\audio_embed_field\Provider\StanfordSoundCloud;
use Drupal\stanford_media\Plugin\media\Source\StanfordOEmbedDeriver;

/**
 * Implements hook_theme_registry_alter().
 */
function stanford_media_theme_registry_alter(&$theme_registry) {
  // Register the path to the template files.
  $path = drupal_get_path('module', 'stanford_media') . '/templates';
  $theme_registry['responsive_image_formatter']['path'] = $path;
  $theme_registry['dropzonejs']['path'] = $path;
}

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function stanford_media_media_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (empty($build['#embed']) || !$build['#embed']) {
    return;
  }

  foreach (_stanford_media_get_dialog_plugins($entity) as $plugin) {
    $plugin->embedAlter($build, $entity);
  }
  $build['#attached']['library'][] = 'stanford_media/display';
}

/**
 * Get a list of all plugins applicable for the entity.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The media entity to check for plugins.
 *
 * @return \Drupal\stanford_media\Plugin\MediaEmbedDialogInterface[]
 *   Array of applicable plugins.
 *
 * @throws \Drupal\Component\Plugin\Exception\PluginException
 */
function _stanford_media_get_dialog_plugins(EntityInterface $entity) {
  $plugins = [];
  /** @var \Drupal\stanford_media\Plugin\MediaEmbedDialogManager $dialog_manager */
  $dialog_manager = \Drupal::service('plugin.manager.media_embed_dialog_manager');
  foreach (array_keys($dialog_manager->getDefinitions()) as $plugin_id) {
    /** @var \Drupal\stanford_media\Plugin\MediaEmbedDialogInterface $plugin */
    $plugin = $dialog_manager->createInstance($plugin_id, ['entity' => $entity]);

    if ($plugin->isApplicable()) {
      $plugins[$plugin_id] = $plugin;
    }
  }
  return $plugins;
}

/**
 * Implements hook_media_source_info_alter().
 */
function stanford_media_media_source_info_alter(array &$sources) {
  $sources['audio_file']['forms']['media_library_add'] = MediaLibraryFileUploadForm::class;
  $sources['file']['forms']['media_library_add'] = MediaLibraryFileUploadForm::class;
  $sources['image']['forms']['media_library_add'] = MediaLibraryFileUploadForm::class;
  $sources['video_file']['forms']['media_library_add'] = MediaLibraryFileUploadForm::class;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function stanford_media_preprocess_dropzonejs(&$variables) {
  // Adds additional things to the template for the dropzone js widget.
  $variables['allowed_files'] = str_replace(' ', ', ', $variables['element']['#extensions']);
  $url = Url::fromRoute('stanford_media.bulk_upload');
  $link = Link::fromTextAndUrl('click here', $url)->toRenderable();
  $link['#attributes']['target'] = '_blank';

  // Only add the help text if you are limited with how many files you can add.
  if ($variables['element']['#max_files']) {
    $variables['help_text'] = t('To bulk upload to the media library %link', ['%link' => render($link)]);
  }
}

/**
 * Implements hook_audio_embed_field_provider_info_alter().
 */
function stanford_media_audio_embed_field_provider_info_alter(&$definitions) {
  $definitions['soundcloud']['class'] = StanfordSoundCloud::class;
}
