stanford_media.embeddable_image_styles:
  type: config_object
  mapping:
    allowed_styles:
      type: sequence
      label: 'Available Styles'
      sequence:
        type: string
        id: "Image style Machine name"

stanford_media.allowed_caption_formats:
  type: config_object
  mapping:
    allowed_formats:
      type: sequence
      label: 'Allowed Image Caption Formats'
      sequence:
        type: string
        id: "Image style Machine name"
