field.formatter.settings.media_image_formatter:
  type: mapping
  label: 'Media Image style formatter settings.'
  mapping:
    view_mode:
      type: string
      label: 'Entity View Mode'
    link:
      type: boolean
      label: 'Link image to parent'
    image_style:
      type: string
      label: 'Image style'
    remove_alt:
      type: boolean
      label: 'Remove the alt text'

field.formatter.settings.media_responsive_image_formatter:
  type: mapping
  label: 'Media responsive image style formatter settings.'
  mapping:
    view_mode:
      type: string
      label: 'Entity View Mode'
    link:
      type: boolean
      label: 'Link image to parent'
    image_style:
      type: string
      label: 'Image style'

field.formatter.settings.media_multimedia_formatter:
  type: mapping
  label: 'Multiple Media Field Formatter'
  mapping:
    view_mode:
      type: string
      label: 'Entity View Mode'
    link:
      type: boolean
      label: 'Link image to parent'
    image_style:
      type: string
      label: 'Image style'
    image:
      label: 'Image formatter settings'
      type: mapping
      mapping:
        image_formatter:
          type: string
          label: 'Image Formatter'
        image_formatter_image_style:
          type: string
          label: 'Image Formatter Option'
        image_formatter_responsive_image_style:
          type: string
          label: 'Responsive Image Formatter Option'
        image_formatter_view_mode:
          type: string
          label: 'Image formatter view mode'
    video:
      label: 'Video formatter settings'
      type: mapping
      mapping:
        video_formatter:
          type: string
          label: 'Video formatter option'
        video_formatter_view_mode:
          type: string
          label: 'Video Formatter view mode'
    other:
      label: 'Other entity types.'
      type: mapping
      mapping:
        view_mode:
          type: string
          label: 'The view mode to fallback to the type.'

field.formatter.settings.embeddable_formatter:
  type: mapping
  label: 'oEmbed display format settings'
  mapping:
    max_width:
      type: integer
      label: 'Maximum width'
    max_height:
      type: integer
      label: 'Maximum height'
    allowed_tags:
      type: string
      label: 'Allowed HTML tags'

media.source.google_form:
  type: media.source.field_aware
  label: '"Google Form" media source configuration'
  mapping:
    source_field:
      type: uri
      label: 'Source field'
    height_field_name:
      type: string
      label: 'The iframe height field'


media.source.embeddable:
  type: media.source.field_aware
  label: '"Embeddable" media source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'
    providers:
      type: sequence
      label: 'Allowed oEmbed providers'
      sequence:
        type: string
        label: 'Provider name'
    oembed_field_name:
      type: uri
      label: 'The field for the oembed link'
    unstructured_field_name:
      type: string
      label: 'The field for the unstructured code'
    source_field:
      type: uri
      label: 'Source field'
    embed_validation:
      type: sequence
      label: 'Embed validation plugin ids'
      sequence:
        type: string
        label: 'Plugin ID'
