field.formatter.settings.media_image_formatter:
  type: mapping
  label: 'Media Image style formatter settings.'
  mapping:
    view_mode:
      type: string
      label: 'Entity View Mode'
    link:
      type: boolean
      label: 'Link image to parent'
    image_style:
      type: string
      label: 'Image style'

field.formatter.settings.media_responsive_image_formatter:
  type: mapping
  label: 'Media responsive image style formatter settings.'
  mapping:
    view_mode:
      type: string
      label: 'Entity View Mode'
    link:
      type: boolean
      label: 'Link image to parent'
    image_style:
      type: string
      label: 'Image style'
