stanford_media.settings:
  type: config_object
  mapping:
    embeddable_image_styles:
      type: sequence
      label: 'Available Styles'
      sequence:
        type: string
        id: "Image style Machine name"
    allowed_caption_formats:
      type: sequence
      label: 'Allowed Image Caption Formats'
      sequence:
        type: string
        id: "Image style Machine name"
